//! What answers for this INSTALL, not for the notebook.
//!
//! The same notebook synced to a phone and a desktop is served by two
//! different binaries, updated two different ways — and only one of them has a
//! menu entry to write. So both things here are machine preferences, and both
//! are refusable: the update check is the one connection the app makes
//! (principle 9), and the menu entry writes two files outside the notebook.

use std::path::PathBuf;

use serde::Serialize;
use tauri::{AppHandle, Runtime};

use crate::error::{CommandError, CommandResult};

/// Whether the app may look for a new version by itself. The settings screen
/// explains the connection this implies and offers this switch to refuse it.
#[tauri::command]
pub fn auto_update_check<R: Runtime>(app: AppHandle<R>) -> bool {
    crate::prefs::auto_update_check(&app)
}

#[tauri::command]
pub fn remember_auto_update_check<R: Runtime>(app: AppHandle<R>, on: bool) {
    crate::prefs::remember_auto_update_check(&app, on);
}

/// When the last automatic check ran — an opaque timestamp the frontend
/// owns, only there to keep the check to once a day.
#[tauri::command]
pub fn last_update_check<R: Runtime>(app: AppHandle<R>) -> Option<String> {
    crate::prefs::last_update_check(&app)
}

#[tauri::command]
pub fn remember_last_update_check<R: Runtime>(app: AppHandle<R>, when: String) {
    crate::prefs::remember_last_update_check(&app, &when);
}

/// The version this binary was built as. Shown in the settings screen, and
/// the "current" side of the update check.
#[tauri::command]
pub fn app_version() -> &'static str {
    env!("CARGO_PKG_VERSION")
}

/// Where the published manifest lives. `latest.json` is generated by the
/// release pipeline next to the installers, and `releases/latest` only
/// resolves once a release is PUBLISHED — which is exactly right, a draft is
/// not an update.
const UPDATE_MANIFEST_URL: &str =
    "https://github.com/Gustavo-Tondin/jott-app/releases/latest/download/latest.json";
/// The page the notice's button opens where the app cannot replace itself.
const RELEASE_PAGE_URL: &str = "https://github.com/Gustavo-Tondin/jott-app/releases/latest";
/// Points the check somewhere else — a local server in a test, a manifest of
/// lies while developing the notice. The one door through which the https
/// fence below is not enforced.
const UPDATE_URL_ENV: &str = "JOTT_UPDATE_URL";
/// More than enough for a manifest that names one version and four installers.
const MAX_MANIFEST_BYTES: u64 = 64 * 1024;

/// What the frontend hears back from a check.
#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct UpdateCheck {
    /// The version running right now.
    pub current: String,
    /// The version the manifest names.
    pub latest: String,
    /// Whether `latest` is strictly newer — the only bit the notice needs.
    pub newer: bool,
    /// Whether THIS install can replace itself (the AppImage, the Windows
    /// build). A .deb/.rpm/pacman install belongs to the package manager and
    /// an APK to Android's installer — there the notice offers `url` instead.
    pub can_install: bool,
    /// The release page, for the installs that cannot.
    pub url: String,
}

/// Asks the release feed for the newest published version.
///
/// The second thing this app does that leaves the machine, after
/// `import_asset_from_url`, and fenced the same way: https only, timeouts on
/// both ends, a size ceiling. Consent is handled a level up — the automatic
/// check is a machine preference the settings screen explains and switches
/// off, so this command only runs because that switch (or a click on
/// "check now") said so.
#[tauri::command]
pub async fn check_for_update() -> CommandResult<UpdateCheck> {
    let (url, overridden) = match std::env::var(UPDATE_URL_ENV) {
        Ok(url) if !url.trim().is_empty() => (url, true),
        _ => (UPDATE_MANIFEST_URL.to_string(), false),
    };
    let latest =
        tauri::async_runtime::spawn_blocking(move || fetch_latest_version(&url, overridden))
            .await
            .map_err(|e| CommandError::new("io", e.to_string()))??;

    let current = env!("CARGO_PKG_VERSION");
    Ok(UpdateCheck {
        current: current.to_string(),
        newer: jott_core::version::is_newer(&latest, current),
        latest,
        can_install: cfg!(windows) || std::env::var_os("APPIMAGE").is_some(),
        url: RELEASE_PAGE_URL.to_string(),
    })
}

fn fetch_latest_version(url: &str, overridden: bool) -> CommandResult<String> {
    use std::io::Read;

    if !overridden && !url.starts_with("https://") {
        return Err(CommandError::new("invalid", format!("{url} is not https")));
    }
    let agent: ureq::Agent = ureq::Agent::config_builder()
        .timeout_connect(Some(std::time::Duration::from_secs(10)))
        .timeout_global(Some(std::time::Duration::from_secs(30)))
        .build()
        .into();

    let mut response = agent
        .get(url)
        .call()
        .map_err(|e| CommandError::new("io", format!("{url}: {e}")))?;

    let mut text = String::new();
    response
        .body_mut()
        .as_reader()
        .take(MAX_MANIFEST_BYTES)
        .read_to_string(&mut text)
        .map_err(|e| CommandError::new("io", e.to_string()))?;

    // Which version a manifest names, and what makes one unusable, is the
    // core's (`jott_core::version`); the bytes are this side's.
    Ok(jott_core::version::from_manifest(&text)?)
}

// ---------------------------------------------------------------------------
// The application menu
// ---------------------------------------------------------------------------

/// The icon the entry points at, carried in the binary.
///
/// Read from the AppImage's own insides instead? It does ship `jott.png` at
/// its root, but reaching it means asking the AppImage to extract itself into
/// a temporary folder — a subprocess, a scratch directory and a dependency on
/// AppImage internals, to fetch twelve kilobytes that are already ours. The
/// same file the PKGBUILD installs, compiled in, cannot go missing.
const ICON_PNG: &[u8] = include_bytes!("../../icons/128x128@2x.png");

/// The entry text, from the file the PKGBUILD installs.
///
/// One template, two installs: whatever the packaged Jott calls itself in the
/// menu, the AppImage calls itself too. Editing `packaging/jott.desktop` moves
/// both, and there is no second copy to forget.
const DESKTOP_TEMPLATE: &str = include_str!("../../../packaging/jott.desktop");

/// What the frontend needs to decide whether to offer, and what to show.
#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct DesktopEntryState {
    /// Whether this install has a menu entry to write at all. False on
    /// Windows, on Android, and on a deb/rpm/pacman Jott — those were put in
    /// the menu by their package manager, and writing a second entry would
    /// give the user two Jotts in the launcher.
    pub supported: bool,
    /// Whether the entry currently on disk points at THIS executable.
    pub installed: bool,
    /// Whether that entry is out of date — it exists and points here, but the
    /// icon or the entry text is not what this build would write. An in-place
    /// update replaces the `.AppImage` and nothing else, so a redrawn icon
    /// would otherwise never reach a machine that integrated months ago.
    pub stale: bool,
    /// Whether the offer was already waved away on this machine.
    pub dismissed: bool,
}

/// Where the running app lives, when it is an AppImage.
///
/// `$APPIMAGE` is set by the AppImage's own runtime to the absolute path of
/// the `.AppImage` file — the same signal `check_for_update` reads to know
/// this install can replace itself. `std::env::current_exe()` is the wrong
/// question here: inside an AppImage it answers with the unpacked binary in a
/// temporary mount that disappears when the app closes.
fn appimage_path() -> Option<PathBuf> {
    let raw = std::env::var_os("APPIMAGE")?;
    let path = PathBuf::from(raw);
    path.is_absolute().then_some(path)
}

/// The user's data directory, per the XDG spec.
///
/// `$XDG_DATA_HOME` first because a machine that sets it means it: writing to
/// `~/.local/share` anyway would put the entry where that desktop is not
/// looking.
fn data_dir() -> Option<PathBuf> {
    match std::env::var_os("XDG_DATA_HOME") {
        Some(dir) if !dir.is_empty() => Some(PathBuf::from(dir)),
        _ => std::env::var_os("HOME").map(|home| PathBuf::from(home).join(".local/share")),
    }
}

#[tauri::command]
pub fn desktop_entry_state<R: Runtime>(app: AppHandle<R>) -> DesktopEntryState {
    let here = appimage_path();
    let dir = data_dir();
    let (installed, stale) = match (&here, &dir) {
        (Some(exec), Some(dir)) => {
            let installed = jott_core::desktop::is_installed(dir, exec);
            let current =
                installed && jott_core::desktop::is_current(dir, DESKTOP_TEMPLATE, exec, ICON_PNG);
            (installed, installed && !current)
        }
        _ => (false, false),
    };
    DesktopEntryState {
        supported: here.is_some() && dir.is_some(),
        installed,
        stale,
        dismissed: crate::prefs::desktop_entry_dismissed(&app),
    }
}

/// Writes the entry, or takes it away again.
///
/// Reversible on purpose: this writes two files outside the notebook, and a
/// feature that can only be turned on is a feature the user cannot undo
/// without being told where the files are.
#[tauri::command]
pub fn set_desktop_entry(on: bool) -> CommandResult<()> {
    let dir = data_dir().ok_or_else(|| {
        CommandError::new("unsupported", "this system has no user data directory")
    })?;

    if !on {
        return jott_core::desktop::remove(&dir).map_err(Into::into);
    }

    let exec = appimage_path()
        .ok_or_else(|| CommandError::new("unsupported", "this install is not an AppImage"))?;
    jott_core::desktop::install(&dir, DESKTOP_TEMPLATE, &exec, ICON_PNG)?;
    Ok(())
}

/// Remembers that the offer was refused, so it is made once and not at every
/// launch.
#[tauri::command]
pub fn dismiss_desktop_entry<R: Runtime>(app: AppHandle<R>) {
    crate::prefs::remember_desktop_entry_dismissed(&app, true);
}

#[cfg(test)]
mod tests {
    use std::path::Path;

    use super::*;

    /// The real template, not a stand-in.
    ///
    /// `jott_core::desktop` is tested against a template of its own, which
    /// proves the rewriting. What it cannot prove is that the file this crate
    /// compiles in is a usable entry — and that file is shared with the
    /// PKGBUILD, so an edit meant for the packaged install lands here too.
    #[test]
    fn the_packaged_template_makes_a_launchable_entry() {
        let exec = Path::new("/home/x/AppImages/Jott.AppImage");
        let icon = Path::new("/home/x/.local/share/icons/hicolor/256x256/apps/jott.png");
        let text = jott_core::desktop::contents(DESKTOP_TEMPLATE, exec, icon);

        assert!(text.starts_with("[Desktop Entry]"));
        for required in ["Type=Application", "Name=Jott", "StartupWMClass=jott"] {
            assert!(text.contains(required), "the entry lost {required}:\n{text}");
        }
        assert!(text.contains("Exec=/home/x/AppImages/Jott.AppImage\n"));
        assert!(text.contains(&format!("Icon={}\n", icon.display())));
        // `Exec=jott` and `Icon=jott` are the packaged install's answers: the
        // first would open nothing from an AppImage, the second is hidden by
        // any stale icon cache. Rewriting both is the whole point.
        assert!(!text.contains("Exec=jott\n"));
        assert!(!text.contains("Icon=jott\n"));
    }

    /// The desktop's own validator, on the entry this crate would write.
    ///
    /// Asserting on the text proves what we MEANT; `desktop-file-validate` is
    /// the freedesktop reference implementation and proves what a launcher
    /// will make of it. Skipped where the tool is absent — that is a missing
    /// measurement, not a failure, and CI must not go red for it.
    #[test]
    fn the_entry_passes_the_freedesktop_validator() {
        let Ok(dir) = tempfile::tempdir() else { return };
        let exec = dir.path().join("Jott.AppImage");
        let entry =
            jott_core::desktop::install(dir.path(), DESKTOP_TEMPLATE, &exec, ICON_PNG).unwrap();

        let Ok(out) = std::process::Command::new("desktop-file-validate")
            .arg(&entry.desktop)
            .output()
        else {
            eprintln!("desktop-file-validate is not installed — entry not validated");
            return;
        };

        // The tool reports hints on stdout and errors through the exit code.
        assert!(
            out.status.success(),
            "the entry is not valid:\n{}",
            String::from_utf8_lossy(&out.stdout)
        );
    }

    /// The icon has to be a PNG the desktop can actually draw: the entry names
    /// it by theme name, so a broken file is an app with no icon rather than
    /// an error anyone sees.
    #[test]
    fn the_compiled_in_icon_is_a_png() {
        assert_eq!(&ICON_PNG[1..4], b"PNG");
        assert!(ICON_PNG.len() > 1024, "that icon is too small to be the real one");
    }

    /// `$HOME` is the fallback, and the spec says an explicit `$XDG_DATA_HOME`
    /// wins — writing to `~/.local/share` on a machine that moved it puts the
    /// entry where nothing is looking.
    #[test]
    fn the_data_directory_follows_the_spec() {
        // Serialised because environment variables belong to the process, not
        // to the test — two of these running at once would read each other's.
        static GUARD: std::sync::Mutex<()> = std::sync::Mutex::new(());
        let _held = GUARD.lock().unwrap_or_else(|e| e.into_inner());

        let restore = (
            std::env::var_os("XDG_DATA_HOME"),
            std::env::var_os("HOME"),
        );

        std::env::set_var("HOME", "/home/x");
        std::env::remove_var("XDG_DATA_HOME");
        assert_eq!(data_dir(), Some(PathBuf::from("/home/x/.local/share")));

        std::env::set_var("XDG_DATA_HOME", "/data");
        assert_eq!(data_dir(), Some(PathBuf::from("/data")));

        // An empty value is not a choice, it is an unset variable spelled out.
        std::env::set_var("XDG_DATA_HOME", "");
        assert_eq!(data_dir(), Some(PathBuf::from("/home/x/.local/share")));

        match restore.0 {
            Some(v) => std::env::set_var("XDG_DATA_HOME", v),
            None => std::env::remove_var("XDG_DATA_HOME"),
        }
        match restore.1 {
            Some(v) => std::env::set_var("HOME", v),
            None => std::env::remove_var("HOME"),
        }
    }

    /// The update check against a real HTTP exchange — a local server, so the
    /// parsing, the ceiling and the error paths are measured on actual bytes
    /// and not on a hand-built context.
    #[test]
    fn update_manifest_is_read_and_judged() {
        use std::io::{Read, Write};

        // One tiny HTTP/1.1 server per body, answering exactly one request.
        fn serve(body: &'static str) -> String {
            let listener = std::net::TcpListener::bind("127.0.0.1:0").unwrap();
            let port = listener.local_addr().unwrap().port();
            std::thread::spawn(move || {
                if let Ok((mut stream, _)) = listener.accept() {
                    let mut buf = [0u8; 2048];
                    let _ = stream.read(&mut buf);
                    let _ = stream.write_all(
                        format!(
                            "HTTP/1.1 200 OK\r\ncontent-length: {}\r\n\r\n{}",
                            body.len(),
                            body
                        )
                        .as_bytes(),
                    );
                }
            });
            format!("http://127.0.0.1:{port}/latest.json")
        }

        // A good manifest: the version comes out.
        let url = serve(r#"{"version": "9.9.9", "platforms": {}}"#);
        assert_eq!(fetch_latest_version(&url, true).unwrap(), "9.9.9");

        // A manifest that is not JSON, and one that names no version: both
        // are "invalid", neither is a phantom update.
        let url = serve("<html>rate limited</html>");
        assert_eq!(fetch_latest_version(&url, true).unwrap_err().kind, "invalid");
        let url = serve(r#"{"notes": "no version here"}"#);
        assert_eq!(fetch_latest_version(&url, true).unwrap_err().kind, "invalid");

        // Off the override door, plain http is refused before any request.
        assert_eq!(
            fetch_latest_version("http://example.com/latest.json", false)
                .unwrap_err()
                .kind,
            "invalid"
        );
    }
}
